version: "3.8"

services:
  goweb-prod:
    build:
      context: .
      dockerfile: ./compose/prod/Dockerfile
    image: europe-west4-docker.pkg.dev/next-js-361720/goweb/goweb-prod:latest
    container_name: goweb-prod
    ports:
      - 8000:8000

  goweb-dev:
    build:
      context: .
      dockerfile: ./compose/dev/Dockerfile
    image: goweb-dev:latest
    container_name: goweb-dev
    volumes:
      - ./:/app
    ports:
      - 8000:8000
